version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: agenda
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/app/
    networks:
      - app
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: db_agenda
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - app
volumes:
  app:
networks:
  app:
    driver: bridge
